### ISSUE TITLE
login failed：countryCode parameter is missing

### ISSUE THREAD

**Issue by aliasmee** [mautrix/twitter#10]
hi，After inputting ct value, login prompt error：
`
Failed to log in: 38: countryCode parameter is missing.
`
Help. Thx

**Comment by bitnexus** [comment]
I'm also having this issue.

**Comment by bitnexus** [comment]
Same issue. Tried a few things to swat at this without any luck. Probably not exhaustive.

1. Create new twitter account
2. Downgrade to v0.1.0 image
3. Kick/reinvite twitterbot

Environment: Kubernetes/Docker
Version: dock.mau.dev/mautrix/twitter:2a8b1df4c870e896dd6c8107a22ab9418b315f6c-amd64 (also v0.1.0)

countryCode does not appear in `/api/1.1/branch/init.json` in twitter request

```
[2021-11-26 21:04:51,641] [DEBUG@mau.mx] Received Matrix event $kBBN1FycQwikzNdbi9UhEVoZCYpHZwDkt4im6sYlx-s from @roy:bitnexus.com in !ntdowgBPECQbFxrHKZ:bitnexus.com
[2021-11-26 21:04:51,867] [ERROR@mau.commands] Failed to log in
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_twitter/commands/auth.py", line 59, in enter_login_cookies
    await evt.sender.connect(auth_token=evt.sender.command_status["auth_token"],
  File "/usr/lib/python3.9/site-packages/mautrix_twitter/user.py", line 125, in connect
    await client.get_user_identifier()
  File "/opt/mautrix-twitter/mautwitdm/twitter.py", line 151, in get_user_identifier
    resp_data = await check_error(resp)
  File "/opt/mautrix-twitter/mautwitdm/errors.py", line 64, in check_error
    raise TwitterError(code, message)
mautwitdm.errors.TwitterError: 38: countryCode parameter is missing.
```
