### ISSUE TITLE
Problem: Missing value for required key entries in InitialStateResponse

### ISSUE THREAD

**Issue by DoM1niC** [mautrix/twitter#4]
I get this Error :( on Python 3.8-3.9 with Postgres
```
matrix-appservice-twitter) matrix@webapps:/home/opt/matrix/bridges/matrix-appservice-twitter$ /home/opt/matrix/bridges/matrix-appservice-twitter/bin/python -m mautrix_twitter
[2020-11-18 04:05:54,757] [INFO@mau.init] Initializing mautrix-twitter 0.1.1+dev.unknown
[2020-11-18 04:05:54,762] [INFO@mau.init] Initialization complete in 0.24 seconds
[2020-11-18 04:05:54,849] [INFO@mau.mx] Ensuring connectivity to homeserver
[2020-11-18 04:05:55,499] [INFO@mau.init] Startup actions complete in 0.74 seconds, now running forever
[2020-11-18 04:05:55,655] [ERROR@mau.user.@dom1nic:matrix.3dns.eu] Exception while syncing conversations
Traceback (most recent call last):
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 3 required positional arguments: 'entries', 'users', and 'conversations'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautrix_twitter/user.py", line 216, in _try_initial_sync
    await self.sync()
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautrix_twitter/user.py", line 230, in sync
    resp = await self.client.inbox_initial_state(set_poll_cursor=False)
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautwitdm/poller.py", line 109, in inbox_initial_state
    response = InitialStateResponse.deserialize(data["inbox_initial_state"])
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 122, in _dict_to_attrs
    raise SerializerError(
mautrix.types.util.serializable.SerializerError: Missing value for required key entries in InitialStateResponse
[2020-11-18 04:05:56,529] [ERROR@mau.twitter.api.@dom1nic:matrix.3dns.eu] Fatal error while polling
Traceback (most recent call last):
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 3 required positional arguments: 'entries', 'users', and 'conversations'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautwitdm/poller.py", line 138, in poll_forever
    await self._poll_forever()
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautwitdm/poller.py", line 163, in _poll_forever
    resp = await self.inbox_initial_state()
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautwitdm/poller.py", line 109, in inbox_initial_state
    response = InitialStateResponse.deserialize(data["inbox_initial_state"])
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/home/opt/matrix/bridges/matrix-appservice-twitter/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 122, in _dict_to_attrs
    raise SerializerError(
mautrix.types.util.serializable.SerializerError: Missing value for required key entries in InitialStateResponse
[2020-11-18 04:05:56,653] [INFO@aiohttp.access] 127.0.0.1 [18/Nov/2020:03:05:56 +0000] "PUT /transactions/34?access_token=iscjdiaihxlo3h3bemcjibzxfoul87ptyvdc16v9wqnmuengm9w42it6bj2tiui8 HTTP/1.1" 200 158 "-" "Synapse/1.22.1"


```

**Comment by tulir** [comment]
That looks a bit like you got logged out or something
